// this is my poor man's VPS. Might upgrade, one day.
// every resource you see in this file is generated by a Python script that I occasionally run.
// as such, not everything on my website might be up to date.

// variable containing gradient colors
var colors = [
    {'from': '#1ABC9C', 'to': '#3498DB', 'bright': true},
    {'from': '#1ABC9C', 'to': '#2980B9', 'bright': false},
    {'from': '#3498DB', 'to': '#9B59B6', 'bright': false},
    {'from': '#3498DB', 'to': '#8E44AD', 'bright': false},
    {'from': '#9B59B6', 'to': '#2980B9', 'bright': false},
    {'from': '#2980B9', 'to': '#8E44AD', 'bright': false},
    {'from': '#F1C40F', 'to': '#E74C3C', 'bright': true},
    {'from': '#F1C40F', 'to': '#D35400', 'bright': true},
    {'from': '#F1C40F', 'to': '#C0392B', 'bright': false},
    {'from': '#E67E22', 'to': '#E74C3C', 'bright': false},
    {'from': '#E67E22', 'to': '#C0392B', 'bright': false},
    {'from': '#E74C3C', 'to': '#F39C12', 'bright': false},
    {'from': '#F39C12', 'to': '#C0392B', 'bright': false}
];

// variable containing subtitles
var strings = [
    'less is more',
    'not a designer',
    'not a full stack programmer',
    'not (yet) an engineer',
    'a good programmer',
    'a creative guy',
    'has many good ideas',
    'eager to learn',
    'can use stackoverflow',
    'visit my GitHub!',
    'likes minimalistic design'
];

// variable containing infos about my repos
var repos = [
    {'name': 'lorenzoros.si-website', 'formatted_name': 'lorenzoros.si website', 'url': 'https://github.com/lorossi/lorenzoros.si-website', 'commits': 65, 'language': 'JavaScript', 'last_pushed_timestamp': '07-11-20T18:23:56:000000'},
    {'name': 'email-hide', 'formatted_name': 'email hide', 'url': 'https://github.com/lorossi/email-hide', 'commits': 26, 'language': 'JavaScript', 'last_pushed_timestamp': '07-11-20T13:01:21:000000'},
    {'name': 'corgos-telegram-bot', 'formatted_name': 'corgos telegram bot', 'url': 'https://github.com/lorossi/corgos-telegram-bot', 'commits': 12, 'language': 'Python', 'last_pushed_timestamp': '07-10-20T13:12:18:000000'},
    {'name': 'zero-width-steganography', 'formatted_name': 'zero width steganography', 'url': 'https://github.com/lorossi/zero-width-steganography', 'commits': 31, 'language': 'Python', 'last_pushed_timestamp': '07-09-20T15:01:32:000000'},
    {'name': 'formulario-campi-elettromagnetici', 'formatted_name': 'formulario campi elettromagnetici', 'url': 'https://github.com/lorossi/formulario-campi-elettromagnetici', 'commits': 34, 'language': 'TeX', 'last_pushed_timestamp': '07-06-20T15:38:41:000000'},
    {'name': 'MicrosoftStreamURLExtractor.github.io', 'formatted_name': 'MicrosoftStreamURLExtractor.github.io', 'url': 'https://github.com/lorossi/MicrosoftStreamURLExtractor.github.io', 'commits': 20, 'language': '', 'last_pushed_timestamp': '06-20-20T09:34:08:000000'},
    {'name': 'pi-day-2020-visualization', 'formatted_name': 'pi day 2020 visualization', 'url': 'https://github.com/lorossi/pi-day-2020-visualization', 'commits': 8, 'language': 'Processing', 'last_pushed_timestamp': '03-14-20T16:38:50:000000'},
    {'name': 'perlin-flow-field', 'formatted_name': 'perlin flow field', 'url': 'https://github.com/lorossi/perlin-flow-field', 'commits': 7, 'language': 'Processing', 'last_pushed_timestamp': '03-01-20T16:30:19:000000'},
    {'name': 'appunti-vhdl', 'formatted_name': 'appunti vhdl', 'url': 'https://github.com/lorossi/appunti-vhdl', 'commits': 12, 'language': 'TeX', 'last_pushed_timestamp': '02-24-20T11:55:50:000000'}
];

// variable containing repos programming languages
var languages = {'TeX': 42.12, 'Python': 28.66, 'JavaScript': 13.15, 'HTML': 6.29, 'Processing': 5.75, 'CSS': 4.03};

// variable containing total bytes of code
var total_bytes = 209386;

// variable containing total number of commits
var total_commits = 215;

// variable containing total number of languages
var total_languages = 6;
