// this is my poor man's VPS. Might upgrade, one day.
// every resource you see in this file is generated by a Python script that I occasionally run.
// as such, not everything on my website might be up to date.

// variable containing gradient colors
var colors = [
    {'from': '#1ABC9C', 'to': '#3498DB', 'bright': true},
    {'from': '#1ABC9C', 'to': '#2980B9', 'bright': false},
    {'from': '#3498DB', 'to': '#9B59B6', 'bright': false},
    {'from': '#3498DB', 'to': '#8E44AD', 'bright': false},
    {'from': '#9B59B6', 'to': '#2980B9', 'bright': false},
    {'from': '#2980B9', 'to': '#8E44AD', 'bright': false},
    {'from': '#F1C40F', 'to': '#E74C3C', 'bright': true},
    {'from': '#F1C40F', 'to': '#D35400', 'bright': true},
    {'from': '#F1C40F', 'to': '#C0392B', 'bright': false},
    {'from': '#E67E22', 'to': '#E74C3C', 'bright': false},
    {'from': '#E67E22', 'to': '#C0392B', 'bright': false},
    {'from': '#E74C3C', 'to': '#F39C12', 'bright': false},
    {'from': '#F39C12', 'to': '#C0392B', 'bright': false}
];

// variable containing subtitles
var strings = [
    'less is more',
    'not a designer',
    'not a full stack programmer',
    'not (yet) an engineer',
    'a good programmer',
    'a creative guy',
    'has many good ideas',
    'eager to learn',
    'can use stackoverflow',
    'visit my GitHub!',
    'likes minimalistic design'
];

// variable containing infos about my repos
var repos = [
    {'name': 'quantomancaanatale', 'formatted_name': 'quantomancaanatale', 'url': 'https://github.com/lorossi/quantomancaanatale', 'commits': 10, 'stars': 0, 'language': 'JavaScript', 'last_pushed_timestamp': '10-12-20T20:15:00:000000', 'created_timestamp': '10-12-20T16:02:58:000000'},
    {'name': 'hexapong', 'formatted_name': 'hexapong', 'url': 'https://github.com/lorossi/hexapong', 'commits': 35, 'stars': 0, 'language': 'JavaScript', 'last_pushed_timestamp': '10-08-20T18:28:56:000000', 'created_timestamp': '10-07-20T19:51:53:000000'},
    {'name': 'lissajous', 'formatted_name': 'lissajous', 'url': 'https://github.com/lorossi/lissajous', 'commits': 18, 'stars': 0, 'language': 'Processing', 'last_pushed_timestamp': '09-07-20T18:57:49:000000', 'created_timestamp': '07-16-20T21:27:05:000000'},
    {'name': 'bikemi-python-unofficial-api', 'formatted_name': 'bikemi python unofficial api', 'url': 'https://github.com/lorossi/bikemi-python-unofficial-api', 'commits': 21, 'stars': 0, 'language': 'Python', 'last_pushed_timestamp': '07-13-20T19:44:22:000000', 'created_timestamp': '07-13-20T11:59:30:000000'},
    {'name': 'rpi-homepage', 'formatted_name': 'rpi homepage', 'url': 'https://github.com/lorossi/rpi-homepage', 'commits': 13, 'stars': 0, 'language': 'Python', 'last_pushed_timestamp': '07-21-20T10:26:16:000000', 'created_timestamp': '07-11-20T16:18:11:000000'},
    {'name': 'lorenzoros.si-website', 'formatted_name': 'lorenzoros.si website', 'url': 'https://github.com/lorossi/lorenzoros.si-website', 'commits': 82, 'stars': 0, 'language': 'JavaScript', 'last_pushed_timestamp': '10-06-20T10:21:46:000000', 'created_timestamp': '07-08-20T16:22:03:000000'},
    {'name': 'email-hide', 'formatted_name': 'email hide', 'url': 'https://github.com/lorossi/email-hide', 'commits': 27, 'stars': 0, 'language': 'JavaScript', 'last_pushed_timestamp': '07-13-20T14:21:52:000000', 'created_timestamp': '07-04-20T17:55:23:000000'},
    {'name': 'MicrosoftStreamURLExtractor.github.io', 'formatted_name': 'MicrosoftStreamURLExtractor.github.io', 'url': 'https://github.com/lorossi/MicrosoftStreamURLExtractor.github.io', 'commits': 20, 'stars': 0, 'language': '', 'last_pushed_timestamp': '06-20-20T09:34:08:000000', 'created_timestamp': '06-20-20T11:34:23:000000'},
    {'name': 'zero-width-steganography', 'formatted_name': 'zero width steganography', 'url': 'https://github.com/lorossi/zero-width-steganography', 'commits': 31, 'stars': 0, 'language': 'Python', 'last_pushed_timestamp': '07-09-20T15:01:32:000000', 'created_timestamp': '06-17-20T09:29:12:000000'},
    {'name': 'corgos-telegram-bot', 'formatted_name': 'corgos telegram bot', 'url': 'https://github.com/lorossi/corgos-telegram-bot', 'commits': 13, 'stars': 0, 'language': 'Python', 'last_pushed_timestamp': '08-01-20T12:48:07:000000', 'created_timestamp': '06-05-20T13:11:52:000000'},
    {'name': 'formulario-campi-elettromagnetici', 'formatted_name': 'formulario campi elettromagnetici', 'url': 'https://github.com/lorossi/formulario-campi-elettromagnetici', 'commits': 35, 'stars': 1, 'language': 'TeX', 'last_pushed_timestamp': '07-23-20T15:45:55:000000', 'created_timestamp': '03-23-20T16:55:33:000000'},
    {'name': 'pi-day-2020-visualization', 'formatted_name': 'pi day 2020 visualization', 'url': 'https://github.com/lorossi/pi-day-2020-visualization', 'commits': 8, 'stars': 0, 'language': 'Processing', 'last_pushed_timestamp': '03-14-20T16:38:50:000000', 'created_timestamp': '03-14-20T16:06:55:000000'},
    {'name': 'perlin-flow-field', 'formatted_name': 'perlin flow field', 'url': 'https://github.com/lorossi/perlin-flow-field', 'commits': 7, 'stars': 0, 'language': 'Processing', 'last_pushed_timestamp': '03-01-20T16:30:19:000000', 'created_timestamp': '03-01-20T16:09:42:000000'},
    {'name': 'appunti-vhdl', 'formatted_name': 'appunti vhdl', 'url': 'https://github.com/lorossi/appunti-vhdl', 'commits': 12, 'stars': 3, 'language': 'TeX', 'last_pushed_timestamp': '02-24-20T11:55:50:000000', 'created_timestamp': '01-16-20T20:16:27:000000'}
];

// variable containing repos programming languages
var languages = {'TeX': 31.59, 'Python': 29.88, 'JavaScript': 19.31, 'Processing': 8.34, 'HTML': 6.21, 'CSS': 4.67};

// variable containing total bytes of code
var total_bytes = 279279;

// variable containing total number of commits
var total_commits = 332;

// variable containing total number of stars
var total_stars = 4;

// variable containing total number of languages
var total_languages = 6;

// variable containing the timestamp of the last update
var timestamp = '2020-10-12T22:18:24.349711';
