function shuffle(a) {
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function randomBetween(min = 0, max = 1) {
  return Math.random() * (max - min) + min;
}

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min) + min);
}

function rotateBackground() {
  $(".background").css({
    "backgroundImage": `linear-gradient(${angle}deg, ${gradient[0]}, ${gradient[1]})`
  });
  angle += 3.6;
}

function selectColors() {
  gradient = colors[Math.floor(Math.random() * colors.length)];
}

function setTextColor(icons_obj) {
  if (gradient[2]) {
    $("body").css({
      "color": dark_color // dark
    });

    $(icons_obj).each(function() {
      $(this).css({
        "filter": dark_filter
      })
    });

  } else {

    $("body").css({
      "color": light_color // light
    });

    $(icons_obj).each(function() {
      $(this).css({
        "filter": light_filter
      })
    });

  }
}

function setProjects(projects_obj) {
  repos.forEach(function(repo, index) {
    let string = `<a href="${repo.url}" target="_blank">${repo.name} - ${repo.commits} commits</a><br>`
    $(projects_obj).append(string);
  });
}

function setSubTitle(subtitle_obj) {
  shuffle(strings);
  if (strings[0] == $(subtitle_obj).text()) {
    random_text = strings[1];
  } else {
    random_text = strings[0];
  }

  $(subtitle_obj).text(random_text);
}

function showText(text_obj, projects_obj, icons_obj, icons_svg_obj) {
  $(text_obj).fadeIn(600, function() {
    $(projects_obj).fadeIn(600, function() {
      $(icons_obj).css({
        "display": "flex"
      })
      $(icons_svg_obj).fadeIn(600)
      //setOrbsContainerSize("#orbs");
    })
  });
}


function moveOrbs(selector) {
  orbs.forEach(function(orb, index) {
    orb.move(mouse_coords);
  });
}


function setOrbsContainerSize(selector) {
  let width, height;
  width = $(".background").width();
  height = $(".background").height();

  if (height != $(selector).height() || width != $(selector).width()) {
    $(selector).css({
      "height": height + "px",
      "width": width + "px"
    })
  }
}


// filter generated by https://codepen.io/sosuke/pen/Pjoqqp
var light_color = "#ddd";
var dark_color = "#131516";
var light_filter = "invert(94%) sepia(1%) saturate(314%) hue-rotate(86deg) brightness(111%) contrast(73%)";
var dark_filter = "invert(5%) sepia(12%) saturate(476%) hue-rotate(155deg) brightness(104%) contrast(93%)";
var angle = 0;
var gradient = [];
var mouse_coords = new Vector(null, null);
var orbs = []

$(document).ready(function() {
  let name_obj = ".title #name";
  let subtitle_obj = ".title #subtitle";
  let text_obj = ".text"
  let projects_obj = ".myprojects #projects"
  let projects_link_obj = ".myprojects #projects a"
  let icons_obj = ".icons";
  let icons_svg_obj = ".icons a";

  let orbs_container_obj = ".orbs";
  let orbs_generated = false;
  let max_orbs = 50;

  selectColors();
  setTextColor(icons_svg_obj);
  setProjects(projects_obj)
  setOrbsContainerSize(orbs_container_obj);


  console.log("%c Curious about this website? Look at the repo here https://github.com/lorossi/lorenzoros.si-website", "font-size: 1.5rem;color:#ddd;background-color:#131516");

  //setTimeout(setSubTitle, 200, name_obj, subtitle_obj);
  setSubTitle(subtitle_obj);
  //setTimeout(showText, 800, text_obj, projects_obj, icons_obj, icons_svg_obj);

  setInterval(setSubTitle, 1000 * 15, subtitle_obj);
  setInterval(setOrbsContainerSize, 1000, orbs_container_obj);

  angle = Math.random() * 360;
  setInterval(rotateBackground, 100);

  $(subtitle_obj).click(
    function() {
      setSubTitle(subtitle_obj);
    }
  );

  $(icons_svg_obj).mouseenter(function() {
    if (gradient[2]) {
      $(this).css({
        "filter": light_filter
      })
    } else {
      $(this).css({
        "filter": dark_filter
      })
    }
  }).mouseleave(function() {
    if (gradient[2]) {
      $(this).css({
        "filter": dark_filter
      })
    } else {
      $(this).css({
        "filter": light_filter
      })
    }
  })

  $(projects_link_obj).mouseenter(function() {
    if (gradient[2]) {
      $(this).css({
        "filter": light_filter
      })
    } else {
      $(this).css({
        "filter": dark_filter
      })
    }
  }).mouseleave(function() {
    if (gradient[2]) {
      $(this).css({
        "filter": dark_filter
      })
    } else {
      $(this).css({
        "filter": light_filter
      })
    }
  })



  $(window).resize(function() {
    setOrbsContainerSize(orbs_container_obj);
  })


  $("body").mousemove(function(e) {
    if (!orbs_generated) {
      orbs_generated = true;
      let radius = 5;
      let width, height;
      width = $(".background").width();
      height = $(".background").height();

      for (let i = 0; i < max_orbs; i++) {
        let x, y;
        x = randomBetween(0, width);
        y = randomBetween(0, height);
        orb = new Orb(x, y, radius, i, orbs_container_obj);
        orbs.push(orb);
      }
      setInterval(moveOrbs, 10, orbs_container_obj);
    }
    mouse_coords.x = e.pageX;
    mouse_coords.y = e.pageY;
  });

})
