function shuffle(a) {
 for (let i = a.length - 1; i > 0; i--) {
  const j = Math.floor(Math.random() * (i + 1));
  [a[i], a[j]] = [a[j], a[i]];
 }
 return a;
}

function rotateBackground() {
 $("body").css({
  "backgroundImage": `linear-gradient(${angle}deg, ${gradient[0]}, ${gradient[1]})`
 });
 angle += 3.6;
}

function selectColors() {
 gradient = colors[Math.floor(Math.random() * colors.length)];
}

function setTextColor(icons_obj) {
 if (gradient[2]) {
  $("body").css({
   "color": dark_color // dark
  });

  $(icons_obj).each(function() {
    $(this).css({
     "filter" : dark_filter
    })
 });

 } else {

  $("body").css({
   "color": light_color // light
  });

  $(icons_obj).each(function() {
    $(this).css({
     "filter" : light_filter
    })
 });

  }
}

function setSubtitle(selector) {
 shuffle(strings);
 if (strings[0] == $(selector).text()) {
  random_text = strings[1];
 } else {
  random_text = strings[0];
 }

 $(selector).text(random_text);
 $(selector).slideDown(300);
}

function showText(selector) {
  console.log(selector);
  $(selector).slideDown(600);
}

function moveOrbs(selector) {
 let easing = 0.03;
 let epsilon = Math.sqrt(1.95);
 let maxvel = 5;
 let width = $(window).width();

 $(selector + ' > div').each(function() {
  let x, y, dx, dy, nx, ny, vel;
  x = $(this).css("left");
  y = $(this).css("top");
  x = parseInt(x.substring(0, x.length - 2)); // remove px and convert to int
  y = parseInt(y.substring(0, y.length - 2));

  dx = (mouse_coords.x - x) * easing;
  dy = (mouse_coords.y - y) * easing;
  vel = Math.sqrt(Math.pow(dx, 2) + Math.pow(dy, 2));

  if (vel > maxvel) {
   dx *= maxvel / vel;
   dy *= maxvel / vel;
  }

  if (vel < epsilon) {
   let r, theta, x, y;

   r = Math.random() * (2 - 1) + 1;

   theta = Math.random() * 2 * Math.PI;
   x = (r * Math.cos(theta) + 1) * 100 + "vw";
   y = (r * Math.sin(theta) + 1) * 100 + "vh";
   $(this).css({
    "left": x,
    "top": y,
   });

  } else {
     x += dx;
     y += dy;
     $(this).css({
      "left": x + "px",
      "top": y + "px",
     });
    }
 });
}


var angle = 0;
var gradient = [];
var mouse_coords = {
 "x": 0,
 "y": 0
};

// filter generated by https://codepen.io/sosuke/pen/Pjoqqp
var light_color = "#ddd";
var dark_color = "#131516";
var light_filter = "invert(95%) sepia(0%) saturate(260%) hue-rotate(187deg) brightness(97%) contrast(87%)";
var dark_filter = "invert(4%) sepia(4%) saturate(1810%) hue-rotate(155deg) brightness(101%) contrast(91%)";


$(document).ready(function() {
 let subtitle_obj = ".title #subtitle";
 let text_obj = ".text"
 let icons_obj = ".icons a";
 let orbs_container_obj = ".orbs";
 let orbs_generated = false;
 let max_orbs = 150;

 selectColors();
 setTextColor(icons_obj);
 angle = Math.random() * 360;

 console.log("%c Curious about this website? Look at the repo here https://github.com/lorossi/lorenzoros.si-website", "font-size: 1.5rem;color:#ddd;background-color:#131516");

 setTimeout(setSubtitle, 200, subtitle_obj);
 setTimeout(showText, 500, text_obj);

 setInterval(setSubtitle, 1000 * 15, subtitle_obj);
 setInterval(rotateBackground, 100);

 $(subtitle_obj).click(
  function() {
   setSubtitle(subtitle_obj);
  }
 );

 $(icons_obj).mouseenter(function() {
   if (gradient[2]) {
     $(this).css({
      "filter" : light_filter
    })
   } else {
     $(this).css({
      "filter" : dark_filter
     })
   }
 }).mouseleave(function() {
   if (gradient[2]) {
     $(this).css({
      "filter" : dark_filter
    })
   } else {
     $(this).css({
      "filter" : light_filter
     })
   }
 })

 $("body").mousemove(function(e) {
   if (!orbs_generated) {
   // here we generate orbs
   orbs_generated = true;
   for (let i = 0; i < max_orbs; i++) {
    let r, theta, x, y;

    r = Math.random() * (2 - 1) + 1;
  //  r = Math.sqrt(2);
    theta = Math.random() * 2 * Math.PI;
    x = (r * Math.cos(theta) + 1) * 100 + "vw";
    y = (r * Math.sin(theta) + 1) * 100 + "vh";

    $("<div>", {
     "id": "orb",
     css: {
      "left": x,
      "top": y
     }
    }).appendTo(orbs_container_obj);
  }
   setInterval(moveOrbs, 10, orbs_container_obj);
  }
  mouse_coords.x = e.pageX;
  mouse_coords.y = e.pageY;
 })
})
