// this is my poor man's VPS. Might upgrade, one day.
// every resource you see in this file is generated by a Python script that I occasionally run.
// as such, not everything on my website might be up to date.

// variable containing gradient colors
var colors = [
    {'from': '#1ABC9C', 'to': '#2ECC71', 'bright': true},
    {'from': '#1ABC9C', 'to': '#3498DB', 'bright': true},
    {'from': '#1ABC9C', 'to': '#27AE60', 'bright': true},
    {'from': '#1ABC9C', 'to': '#2980B9', 'bright': true},
    {'from': '#2ECC71', 'to': '#3498DB', 'bright': true},
    {'from': '#2ECC71', 'to': '#2980B9', 'bright': true},
    {'from': '#3498DB', 'to': '#9B59B6', 'bright': false},
    {'from': '#3498DB', 'to': '#27AE60', 'bright': true},
    {'from': '#3498DB', 'to': '#8E44AD', 'bright': false},
    {'from': '#9B59B6', 'to': '#2980B9', 'bright': false},
    {'from': '#27AE60', 'to': '#2980B9', 'bright': false},
    {'from': '#2980B9', 'to': '#8E44AD', 'bright': false},
    {'from': '#F1C40F', 'to': '#E74C3C', 'bright': true},
    {'from': '#F1C40F', 'to': '#D35400', 'bright': true},
    {'from': '#F1C40F', 'to': '#C0392B', 'bright': true},
    {'from': '#E67E22', 'to': '#E74C3C', 'bright': false},
    {'from': '#E67E22', 'to': '#C0392B', 'bright': false},
    {'from': '#E74C3C', 'to': '#F39C12', 'bright': true},
    {'from': '#F39C12', 'to': '#C0392B', 'bright': false}
];

// variable containing subtitles
var strings = [
    'not a designer',
    'not a full stack programmer',
    'not (yet) an engineer',
    'a good programmer',
    'a creative guy',
    'has many good ideas',
    'eager to learn',
    'can use stackoverflow',
    'visit my GitHub!',
    'likes minimalistic design'
];

// variable containing infos about my repos
var repos = [
    {'name': 'lorenzoros.si-website', 'url': 'https://github.com/lorossi/lorenzoros.si-website', 'commits': 36, 'language': 'JavaScript'},
    {'name': 'formulario-campi-elettromagnetici', 'url': 'https://github.com/lorossi/formulario-campi-elettromagnetici', 'commits': 34, 'language': 'TeX'},
    {'name': 'zero-width-steganography', 'url': 'https://github.com/lorossi/zero-width-steganography', 'commits': 31, 'language': 'Python'},
    {'name': 'email-hide', 'url': 'https://github.com/lorossi/email-hide', 'commits': 24, 'language': 'JavaScript'},
    {'name': 'MicrosoftStreamURLExtractor.github.io', 'url': 'https://github.com/lorossi/MicrosoftStreamURLExtractor.github.io', 'commits': 20, 'language': ''},
    {'name': 'appunti-vhdl', 'url': 'https://github.com/lorossi/appunti-vhdl', 'commits': 12, 'language': 'TeX'},
    {'name': 'corgos-telegram-bot', 'url': 'https://github.com/lorossi/corgos-telegram-bot', 'commits': 12, 'language': 'Python'},
    {'name': 'pi-day-2020-visualization', 'url': 'https://github.com/lorossi/pi-day-2020-visualization', 'commits': 8, 'language': 'Processing'},
    {'name': 'perlin-flow-field', 'url': 'https://github.com/lorossi/perlin-flow-field', 'commits': 7, 'language': 'Processing'}
];